branches:
- main
debug: true
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "semantic-release-python":
    setupPy: "./pyproject.toml"
    pypiPublish: true


prepare:
  - "semantic-release-python"
verifyConditions: "@semantic-release/github"
publish:
  - "@semantic-release/github"
  - "semantic-release-python"
analyzeCommits:
  releaseRules:
  - type: fix
    release: patch
  - type: perf
    release: patch
  - type: refactor
    release: patch
  - type: build
    release: patch
  - type: ci
    release: patch
  - type: feat
    release: minor
  - type: feature
    release: minor
  - type: breaking
    release: major
  - type: chore
    release: patch

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    linkCompare: true
    linkReferences: true
    presetConfig:
      types:  # looks like it only works with 'conventionalcommits' preset
      - type: fix
        release: patch
        hidden: false
      - type: perf
        release: patch
        hidden: false
      - type: refactor
        release: patch
        hidden: false
      - type: build
        release: patch
        hidden: false
      - type: ci
        release: patch
        hidden: false
      - type: feat
        release: minor
        hidden: false
      - type: feature
        release: minor
        hidden: false
      - type: breaking
        release: major
        hidden: false
      - type: chore
        release: patch
        hidden: false