branches:
- main
debug: true
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "semantic-release-python":
    setupPy: "./pyproject.toml"
    pypiPublish: true
- "@semantic-release/github":
    assets: [ "./pyproject.toml" ]
