branches:
- name: main
- name: "PF-[0-9]*"
  channel: b
  prerelease: b
debug: true
plugins:
- "@semantic-release/commit-analyzer":
  releaseRules:
    - type: fix
      release: patch
    - type: perf
      release: patch
    - type: refactor
      release: patch
    - type: build
      release: patch
    - type: ci
      release: patch
    - type: feat
      release: minor
    - type: feature
      release: minor
    - type: breaking
      release: major
    - type: chore
      release: patch
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog":
    "changelogFile": "CHANGELOG.md"
- "semantic-release-python":
    setupPy: "./pyproject.toml"
- "@semantic-release/git":
    assets: ["pyproject.toml", "!package.json", "!package-lock.json"]
    message: "TTTTT chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
- "@semantic-release/github":
    assets: [ "./pyproject.toml" ]


verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

analyzeCommits:
  - "@semantic-release/commit-analyzer"

prepare:
  - path: "@semantic-release/changelog"
  - path: "semantic-release-python"
  - path: "@semantic-release/git"

publish:
  - "@semantic-release/github"

addChannel:
  - "@semantic-release/github"
